language: node_js

script:
  - cat ~/.ssh/id_rsa.pub
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis-ci"
  - (cd happychips && npm install)
  - (cd happychips && hexo generate --deploy)

