language: node_js

script:
  - cat /etc/ssh/ssh_config
  - echo "Host *" > ~/.ssh/config
  - echo "  BatchMode yes" >> ~/.ssh/config
  - echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.ssh/id_rsa
  - echo $HEHU >> ~/.ssh/id_rsa 
  - echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo $HEHUU > ~/.ssh/id_rsa.pub
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis-ci"
  - (cd happychips && npm install)
  - (cd happychips && hexo generate)
  - mkdir test
  - (cd deploy && git clone git@github.com:kbeckmann/kbeckmann.github.io.git)
  - (cd deploy && rm -rf * && cp -rvp ../happychips/public/* . && git add . && git commit -m "Wee" && git push origin master)

