language: node_js

script:
  - cat /etc/ssh/ssh_config
  - echo $HEHU > ~/.ssh/id_rsa_new
  - echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.ssh/id_rsa
  - fold -w 64 ~/.ssh/id_rsa_new >> ~/.ssh/id_rsa
  - echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis-ci"
  - (cd happychips/themes/hexo-theme-next && git fetch && git checkout hexo-theme-next)
  - (cd happychips && npm install)
  - (cd happychips && hexo generate --deploy)
